
#_base: [portfolios/sep23]

container:
  _type: context

  gadgets:
    common._type: common-stats
#    yahoo:
#      _type: scope
#
#      gadgets:
    loader._type: yahoo-loader
    info._type: yahoo-info

    ib._type: ibkr-simple

#    portfolio-loader: <>portfolio
    portfolio:
      _type: portfolio-loader
#      name: <>portfolio-name
#      portfolio: <>full-portfolio



