
#_base: [container, euro]
#
#_meta.script_name: euro-stats
#
#portfolio.name: fe-aug23.txt
#
#date: 230909
#
#overwrite: yes
##ignore-errors: yes



################


#_meta.script_name: ib-search
#
##yf: MC.PA
##currency: EUR
#
#q: STLA
#currency: USD
#
#auto: yes


################


_base: [dl/yf, dl/ib]

_meta.script_name: download

date: 230909

#tickers: [CON.DE]





