
_base: [container, euro]

_meta.script_name: euro-stats

#outpath: assets/euro-stats-sep9.csv
#outpath: assets/euro-stats-sep28.csv
outpath: assets/euro-stats-stoxx50.csv

#portfolio-name: fe-aug23.txt

#date: 230909
date: 230928

#overwrite: yes
#ignore-errors: yes



################


#_meta.script_name: ib-search
#
##yf: MC.PA
##currency: EUR
#
#q: STLA
#currency: USD
#
#auto: yes


################


##_base: [dl/yf, dl/ib, dl/av]
#_base: [dl/av]
#
#_meta.script_name: download
#
#date: 230909
#
##tickers: [CON.DE]





