

Japan: EWJ
China: ASHR
Colombia: GXG
Denmark: EDEN
Egypt: EGPT
Brazil: EWZ
Taiwan: EWT
Russia: RSX
#Russia: ERUS
Germany: EWG
France: EWQ
Austria: EWO
Belgium: EWK
Netherlands: EWN
Greece: GREK
Hong Kong: EWH
Thailand: THD
Turkey: TUR
Vietnam: VNM
Italy: EWI
Mexico: EWW
#New Zealand: EWZL
Finland: EFNL
Peru: EPU
Poland: EPOL
Canada: EWC
United Kingdom: EWU
India: INDA
#India: PIN
Indonesia: EIDO
#Indonesia: IDX
Ireland: EIRL
Israel: EIS
South Korea: EWY
Sweden: EWD
Australia: EWA
Malaysia: EWM
Singapore: EWS
Spain: EWP
Switzerland: EWL
South Africa: EZA
United States: SPY

